// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2GEyn1Ldz1r4mjD_uORDZWQ9ZPy0CbPw',
    appId: '1:536376716304:web:4c495984515804994f6e95',
    messagingSenderId: '536376716304',
    projectId: 'testeteste-4029a',
    authDomain: 'testeteste-4029a.firebaseapp.com',
    storageBucket: 'testeteste-4029a.appspot.com',
    measurementId: 'G-KKGDDD0CJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiGHUbR5F9FpnlVLmvAtywuPbuXsSq1c0',
    appId: '1:536376716304:android:1e0ef7cffc7ff2614f6e95',
    messagingSenderId: '536376716304',
    projectId: 'testeteste-4029a',
    storageBucket: 'testeteste-4029a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG162cqFjbu5mjFNRMZIwV9eIFU6A9iu0',
    appId: '1:536376716304:ios:f9e5f9f0b08560814f6e95',
    messagingSenderId: '536376716304',
    projectId: 'testeteste-4029a',
    storageBucket: 'testeteste-4029a.appspot.com',
    iosClientId: '536376716304-kq7q0lr8tdceasa89u25oc6hqbd87rtc.apps.googleusercontent.com',
    iosBundleId: 'com.example.exemplo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG162cqFjbu5mjFNRMZIwV9eIFU6A9iu0',
    appId: '1:536376716304:ios:f9e5f9f0b08560814f6e95',
    messagingSenderId: '536376716304',
    projectId: 'testeteste-4029a',
    storageBucket: 'testeteste-4029a.appspot.com',
    iosClientId: '536376716304-kq7q0lr8tdceasa89u25oc6hqbd87rtc.apps.googleusercontent.com',
    iosBundleId: 'com.example.exemplo',
  );
}
